name: Publish
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - uses: docker/metadata-action@v5
      id: metadata
      with:
        images: ghcr.io/${{ github.repository }}
        labels: |
            org.opencontainers.image.description=Processing images to extract metadata and write to cloud storage
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
